default: &default
  adapter: postgresql
  username: postgres
  password: root
  host: 127.0.0.1
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: films_development

test:
  <<: *default
  database: films_test